# Numpy 
NumPy (Numerical Python) is a Python library used for fast numerical computations.
It provides:

Multi-dimensional array object (ndarray) for storing and manipulating large datasets.

Mathematical functions for operations like linear algebra, statistics, and Fourier transforms.

Broadcasting for efficient element-wise operations without writing loops.

Integration with other libraries like Pandas, SciPy, and scikit-learn.

In short — NumPy makes Python super fast for working with numbers and arrays, especially in data science, machine learning, and scientific computing.

In [ ]:
# importing numpy
import numpy as np

In [ ]:
### 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))


In [ ]:
arr1.reshape((5,1))

In [ ]:
### 2d array

arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)
print(arr2.shape)

In [ ]:
### creating array with built in methods

np.arange(1,10,1).reshape(9,1)


In [ ]:
# ones
np.ones((3,5))

In [ ]:
np.zeros((3,5))

In [ ]:
## identity matrix
np.eye(3)

In [ ]:
time = 0.4
tempreature = 34
time-tempreature



In [ ]:
### numpy vectarized operation 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print("addition" , arr1 + arr2 )
print("sub :" , arr1 - arr2)
print("div" , arr1/arr2)
print("mul" , arr1 * arr2 )

In [ ]:
arr=np.array([1,2,3,4])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

In [46]:
arr=np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
arr[0][3]

np.int64(4)

In [ ]:
print(np.mean(arr2))
print(np.median(arr2))
print(np.matrix_transpose(arr))
print(arr)
print(np.angle(arr))
print(np.argmax(arr))

#### numpy creating arrays with methods 


In [43]:
np.full((2,4),111)
ran=np.random.random((4,4)) ** 4
print(ran)

[[1.86356597e-08 1.93351530e-07 1.51269593e-03 7.98834428e-03]
 [9.21662974e-01 3.47794106e-02 5.20934042e-05 7.84772543e-01]
 [7.99444261e-01 1.32920364e-03 2.28155631e-03 2.26921196e-01]
 [7.88349298e-01 4.15691821e-01 6.68717783e-02 1.14746984e-01]]


In [ ]:
### array slicing and indexing
arr=np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])
print(arr[0,3])
print(arr[:,4])
print(arr[2])


4
[ 5 50 55]
[11 22 33 44 55]


In [69]:
### Filter with mask
mask = arr%2==0
print(arr[mask])

[ 2  4 10 20 30 40 50 22 44]


In [81]:
number = np.array([1,2,3,4,5,6,7,8,9,10])

In [82]:
# fancy indexing
indices=[[0,1],[2,1]]
number[indices]

array([[1, 2],
       [3, 2]])

In [83]:
### where()
result=np.where(number>5)
number[result]

array([ 6,  7,  8,  9, 10])

In [89]:
## condition array
ca=np.where(number >=3 , number**2 , number)
print(ca)

[  1   2   9  16  25  36  49  64  81 100]


##### numpy is complete